name: headset_connection_event
description: Flutter Plugin for headset events. Detect headset is plugged and unplugged. Get current headset state.
version: 1.0.0
author: songyiYu<songyi0207@gmail.com>, yenoss<cpg0504@gmail.com>, FlutterMoum Group<fluttermoum@gmail.com>, Blake Helms (helmsb), Rafael Delos Santos (themobilecoder)
homepage: https://github.com/themobilecoder/headset_connection_event

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: HeadsetEventPlugin
      android:
        package: flutter.moum.headset_event
        pluginClass: HeadsetEventPlugin
